### PR TITLE
Fix VM cleanup issue and improve VM deletion logic for containerd periodic jobs

### LINKED ISSUE #311: VM not cleaned up when tests fail to start due to some early issues
## Problem
If tests fail to start due to an early failure (for example, inability to connect to the VM), the created VM is not getting deleted.
This results in VMs being created but never cleaned up.

##Fix
PR: #310

### PR DESCRIPTION
**Pull request by bharti-0211**
Ensures VM deletion in all cases even if the tests don't start running at all because of some early issue like inability to connect to the VM.
Fixes #311

### CODE REVIEW

**Comment by anup-kodlekere** [comment]
I am okay with these changes for now. I will raise another PR once this is merged to improve robustness of the scripts.

File: test-containerd/instantiate_vm_and_test.sh [hunk 1]
```diff
@@ -60,6 +61,20 @@ function delete_network() {
...
+    echo "Cleaning up VM $ID"
+    delete_vm "$ID"
+    sleep 120
+  fi
+  if [ -n "${NETWORK:-}" ]; then
+    echo "Cleaning up network $NETWORK"
+    delete_network "$NETWORK"
+  fi
+}
+trap cleanup EXIT
```
Comment (AshwinHIBM) [inline test-containerd/instantiate_vm_and_test.sh]: Won't you be able to pass in the `ID` as an argument if you move this statement below where the `ID` gets assigned? That'll also eliminate the `ID` declaration at the top.

File: test-containerd/instantiate_vm_and_test.sh [hunk 2]
```diff
@@ -60,6 +61,20 @@ function delete_network() {
   return $NET_DEL_EXIT
 }
 
+function cleanup() {
+  set +e
+  if [ -n "${ID:-}" ]; then
```
Comment (AshwinHIBM) [inline test-containerd/instantiate_vm_and_test.sh]:
```suggestion
  if [[ -n "${ID:-}" ]]; then
```

File: test-containerd/instantiate_vm_and_test.sh [hunk 3]
```diff
@@ -107,7 +122,7 @@ while [ $i -lt $TIMEOUT ] && [ -z "$(ibmcloud pi instance get $ID | grep 'Extern
   sleep 60
 done
 # Fail to connect
-if [ "$i" == "$TIMEOUT" ]; then echo "FAIL: fail to get IP" ; delete_vm $ID; sleep 120; delete_network $NETWORK; exit 1; fi
+if [ "$i" == "$TIMEOUT" ]; then echo "FAIL: fail to get IP" ; exit 1; fi
```
Comment (AshwinHIBM) [inline test-containerd/instantiate_vm_and_test.sh]:
```suggestion
if [[ "$i" == "$TIMEOUT" ]]; then 
   echo "FAIL: fail to get IP"
   exit 1
fi
```

File: test-containerd/instantiate_vm_and_test.sh [hunk 4]
```diff
@@ -60,6 +61,20 @@ function delete_network() {
...
 }
 
+function cleanup() {
+  set +e
+  if [ -n "${ID:-}" ]; then
+    echo "Cleaning up VM $ID"
+    delete_vm "$ID"
+    sleep 120
+  fi
+  if [ -n "${NETWORK:-}" ]; then
```
Comment (AshwinHIBM) [inline test-containerd/instantiate_vm_and_test.sh]:
```suggestion
  if [[ -n "${NETWORK:-}" ]]; then
```

File: test-containerd/instantiate_vm_and_test.sh [hunk 5]
```diff
@@ -35,7 +36,7 @@ function delete_vm() {
 }
 
 function delete_network() {
-  if [ -z $1 ]; then echo "Nothing to delete. delete_network requires the network ID as an argument."; return; fi
+  if [ -z "${1:-}" ]; then echo "Nothing to delete. delete_network requires the network ID as an argument."; return; fi
```
Comment (AshwinHIBM) [inline test-containerd/instantiate_vm_and_test.sh]:
```suggestion
  if [[ -z "${1:-}" ]]; then
     echo "Nothing to delete. delete_network requires the network ID as an argument."
     return
  fi
```

File: test-containerd/instantiate_vm_and_test.sh [hunk 6]
```diff
@@ -26,7 +27,7 @@ EOF
 }
 
 function delete_vm() {
-  if [ -z $1 ]; then echo "Nothing to delete. delete_vm requires the vm ID as an argument."; return; fi
+  if [ -z "${1:-}" ]; then echo "Nothing to delete. delete_vm requires the vm ID as an argument."; return; fi
```
Comment (AshwinHIBM) [inline test-containerd/instantiate_vm_and_test.sh]:
```suggestion
  if [[ -z "${1:-}" ]]; then 
     echo "Nothing to delete. delete_vm requires the vm ID as an argument." 
     return 
  fi
```

**Comment by AshwinHIBM** [comment]
Trying to adapt https://google.github.io/styleguide/shellguide.html in every new PR.

**Comment by AshwinHIBM** [comment]
Can you squash the commits?

**Comment by clnperez** [comment]
LGTM
